#pragma once
#define MAX_INSTANCE_COUNT 1000000
#define MAX_SUBSCENE_INSTANCE_COUNT 500

#define MAX_BONE_INSTANCE_COUNT 7500
#define MAX_SUBSCENE_BONE_INSTANCE_COUNT 100

#define MAX_LINE_BATCH_COUNT 1000
#define MAX_BILLBOARD_BATCH_COUNT 1000

#define MAX_INDIRECT_COMMANDS 100000 // this could be changed.
#define MAX_SUBSCENE_INDIRECT_COMMANDS 100

#define MAX_INDIRECT_PARTICLE_COMMANDS 200

#define MAX_MESH_BATCH_COUNT 300u
#define MAX_MESH_BATCH_ZERO_INDEXED (MAX_MESH_BATCH_COUNT - 1)

#define MAX_BONE_COUNT 128

#define FF_MT_RENDERING 1
